name : Test Pipeline

on: 
  push:
    branch:
      - f13 


jobs:
  test:
    runs-on: Latest-ubuntu
    steps:
     - name: Build step
       run:  Echo "Building Application"

  sample:
    runs-on: ubuntu-Latest
    steps:
      - name : Test
        run : echo "Test Run"